services:
  rcc1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    networks:
      - app-network

  rcc2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
