services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client1
    volumes:
      - ./data:/data
    networks:
      - app-network
  client2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client2
    volumes:
      - ./data:/data
    networks:
      - app-network
  client3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client3
    volumes:
      - ./data:/data
    networks:
      - app-network

  # clientuser:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-user
  #   container_name: clientuser
  #   volumes:
  #     - ./data:/data
  #   networks:
  #     - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - client1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
