services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./data:/data
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./data:/data
    networks:
      - app-network

  clientuser:
    build:
      context: .
      dockerfile: Dockerfile-user
    container_name: clientuser
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
